CREATE TABLE IF NOT EXISTS contest_diploma_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contest_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255) DEFAULT NULL,
    body_text TEXT,
    award_text TEXT,
    contest_name_text VARCHAR(255) DEFAULT NULL,
    easter_text TEXT,
    signature_1 VARCHAR(255) DEFAULT NULL,
    signature_2 VARCHAR(255) DEFAULT NULL,
    position_1 VARCHAR(255) DEFAULT NULL,
    position_2 VARCHAR(255) DEFAULT NULL,
    footer_text TEXT,
    city VARCHAR(120) DEFAULT NULL,
    issue_date DATE DEFAULT NULL,
    diploma_prefix VARCHAR(32) DEFAULT 'EASTER',
    show_date TINYINT(1) NOT NULL DEFAULT 1,
    show_number TINYINT(1) NOT NULL DEFAULT 1,
    show_signatures TINYINT(1) NOT NULL DEFAULT 1,
    show_background TINYINT(1) NOT NULL DEFAULT 1,
    show_frame TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_contest_template (contest_id),
    CONSTRAINT fk_contest_diploma_templates_contest FOREIGN KEY (contest_id) REFERENCES contests(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS participant_diplomas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contest_id INT NOT NULL,
    application_id INT NOT NULL,
    participant_id INT NOT NULL,
    user_id INT NOT NULL,
    diploma_number VARCHAR(64) NOT NULL,
    file_path VARCHAR(255) DEFAULT NULL,
    public_token CHAR(48) NOT NULL,
    email_sent_at DATETIME DEFAULT NULL,
    generated_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_participant_diploma (participant_id),
    UNIQUE KEY uniq_diploma_number (diploma_number),
    UNIQUE KEY uniq_public_token (public_token),
    KEY idx_application (application_id),
    KEY idx_user (user_id),
    KEY idx_contest (contest_id),
    CONSTRAINT fk_participant_diplomas_contest FOREIGN KEY (contest_id) REFERENCES contests(id) ON DELETE CASCADE,
    CONSTRAINT fk_participant_diplomas_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT fk_participant_diplomas_participant FOREIGN KEY (participant_id) REFERENCES participants(id) ON DELETE CASCADE,
    CONSTRAINT fk_participant_diplomas_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
