CREATE TABLE IF NOT EXISTS participant_number_counters (
    contest_id INT NOT NULL PRIMARY KEY,
    last_ordinal INT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
