CREATE TABLE IF NOT EXISTS export_archive_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    status ENUM('draft','processing','done','error') NOT NULL DEFAULT 'draft',
    filters_json JSON NULL,
    applications_count INT UNSIGNED NOT NULL DEFAULT 0,
    participants_count INT UNSIGNED NOT NULL DEFAULT 0,
    archive_file_path VARCHAR(500) NULL,
    archive_file_name VARCHAR(255) NULL,
    archive_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
    progress_stage VARCHAR(120) NULL,
    error_message TEXT NULL,
    created_by_admin_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_export_archive_jobs_status (status),
    KEY idx_export_archive_jobs_created_at (created_at),
    KEY idx_export_archive_jobs_admin (created_by_admin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
